# Generated by Django 4.2.16 on 2024-12-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_one_name', models.CharField(max_length=100)),
                ('player_two_name', models.CharField(max_length=100)),
                ('player_one_score', models.IntegerField()),
                ('player_two_score', models.IntegerField()),
                ('game_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
