# Generated by Django 4.2.16 on 2024-11-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pongApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='tournament_id',
        ),
    ]
