# Generated by Django 4.2.16 on 2024-12-03 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongApp', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Busy', 'Busy')], default='Offline', max_length=50),
        ),
    ]
