# Generated by Django 4.2.16 on 2024-12-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongApp', '0003_remove_account_is_active_account_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bar_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
